### ISSUE TITLE
Exception with recent upgrade to requests

### ISSUE THREAD

**Issue by got-root** [linkedin/pyexchange#49]
Getting an exception when upgrading from requests==2.6.0 to 2.6.1:  

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/LabStaff/alejandror/Envs/cs_web/lib/python2.7/site-packages/pyexchange/exchange2010/__init__.py", line 769, in find_folder
    response_xml = self.service.send(body)
  File "/home/LabStaff/alejandror/Envs/cs_web/lib/python2.7/site-packages/pyexchange/base/soap.py", line 35, in send
    return self._parse(response, encoding=encoding)
  File "/home/LabStaff/alejandror/Envs/cs_web/lib/python2.7/site-packages/pyexchange/base/soap.py", line 42, in _parse
    raise FailedExchangeException(u"Unable to parse response from Exchange - check your login information. Error: %s" % err)
FailedExchangeException: Unable to parse response from Exchange - check your login information. Error: Start tag expected, '<' not found, line 1, column 1
```

This happens with any request to the server.  Ran the py.test and everything came out good, might not have a test around this.

**Comment by got-root** [comment]
And it looks like it was just fixed in version 2.6.2 a couple of hours ago:  
https://github.com/kennethreitz/requests/issues/2561
